-- insert recipes

INSERT INTO Recipes ( Recipes_Name, Description, Cooking_instructions ) VALUES
('Egibhiibaaii','Hddf fbegc cdhbgb iddahi','Hfbi bbfid dgdegb bhiefh'),
('Hfifbbigdbad','Agch eccei adgaah fiadbh','Hgbi bhbee didggf hccihi'),
('Ghdehbhibcdi','Ebbh cgafa hcbaeg afcgdh','Dgeh ccfac chbfdd eiacfe'),
('Beeigedcbhhc','Cdac dfhcf bdcdfb aighff','Ghhi afgae aaacad ahadfh'),
('Edacigbgecea','Dich ahidc eibbia ffceba','Fbfd fifhe bhhifd cffiga'),
('Ihiaacbhhfed','Ffbg fcaah biggae idaiei','Adei ecdac efhgfi ccgfeb'),
('Degdagedhhfh','Fche ihcag bhdgbh hgccdh','Hgac dfdib dhabbi bfhghe'),
('Ffhceabaebfe','Fbhb efeeb afhdea gcgefd','Igig idhbf hfbeca hgaddd'),
('Difefdfiidbb','Cheh fagfc difhdd effcbb','Ddha ahhgb gcbhcc igiacd'),
('Gifiaicafhah','Idda fdcfa hgdgfe hcbfef','Hbde ccigh addcbf cffcfi'),
('Cdicgbbaddab','Biac gaebc aafbbb fhadff','Dgfd bfacb iabfae eadfce'),
('Eeedegehaiac','Hebf eegbf badbbc eibiic','Fbgc hbehb dgfagd cgcgia'),
('Iigegicffcbh','Dafi dcebd dhfigf bfgica','Ecac chbhb ccgceb gchdgd'),
('Ibgighebgfbh','Gafc haeeb heihhe iehcbh','Fcia hfcbb icbehh dgcbhd'),
('Fbibbaeffadi','Ciaa cadda dcbcia gdaeih','Gdfd ifhhc daaige fhdhfb'),
('Affghbihheac','Abbb begah bcbacb igieie','Biha cdfch ffhgah baedfi'),
('Ibagcifiaddd','Eagb aiaai fhfiei gibdeh','Iibd afbif iehhbd acgeaf'),
('Ihbbeadghfea','Gfid hiiad cchgie gheibb','Gfhb ggccb gaebaa bdiiga'),
('Aifbabaigbdi','Eech ggaaa hhacff fdfdeh','Fbgf bdgeh bdfeeb hfcbfd'),
('Ggghadaecbaa','Iihg ahefi ahficd fecede','Afih fdbgi iiieeh eiafad'),
('Eahffbbcfdch','Diie cdbfb fdbacc hgiadc','Giha bgdaf dbifec aeacfg'),
('Iidefddibcbg','Ebaa abgca eiccdc fdfcgd','Iech bcafc acfibg bhfieh'),
('Bgdfegcciecc','Hgbb edgbd haghfa ahiigb','Dfad bahae aibeff acbgaf'),
('Caiffeaaedgc','Habg aieeh fcaafi ciccef','Gabc biadi aecgfc cfbcag'),
('Ccdghbbhdgid','Beeh bbifa dghfbf deabhg','Ebgb ceifc ibedab gccfai');